// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlD5H3QDvnt0sHyHKlW433E_zzDdgZZxg',
    appId: '1:628869147201:web:36e1d62bcc67a4d0a8b4c0',
    messagingSenderId: '628869147201',
    projectId: 'tulpar-chat-xetz',
    authDomain: 'tulpar-chat-xetz.firebaseapp.com',
    storageBucket: 'tulpar-chat-xetz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsInjuVWvTRgsovvDXQuTkNzKxAb6KZDI',
    appId: '1:628869147201:android:1d836ca53621070ca8b4c0',
    messagingSenderId: '628869147201',
    projectId: 'tulpar-chat-xetz',
    storageBucket: 'tulpar-chat-xetz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxjQsCU171shX7tKstJRaWP7m2kNrKlno',
    appId: '1:628869147201:ios:3aded173d8b2043ba8b4c0',
    messagingSenderId: '628869147201',
    projectId: 'tulpar-chat-xetz',
    storageBucket: 'tulpar-chat-xetz.appspot.com',
    iosClientId: '628869147201-k97roa6kgsh72a6cjve0t6507s96qjbf.apps.googleusercontent.com',
    iosBundleId: 'com.example.tulparChatApp',
  );
}
